// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using proyecto_venta_stock.Data;

#nullable disable

namespace proyecto_venta_stock.Migrations
{
    [DbContext(typeof(VentaStockContext))]
    [Migration("20260323232338_SoporteUnidadesDecimales")]
    partial class SoporteUnidadesDecimales
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pgcrypto");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("proyecto_venta_stock.Models.Auditoria", b =>
                {
                    b.Property<long>("IdAuditoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id_auditoria");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("IdAuditoria"));

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("accion");

                    b.Property<string>("Detalle")
                        .HasColumnType("text")
                        .HasColumnName("detalle");

                    b.Property<string>("EntidadId")
                        .HasColumnType("text")
                        .HasColumnName("entidad_id");

                    b.Property<string>("EntidadTipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("entidad_tipo");

                    b.Property<DateTimeOffset>("FechaHora")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("fecha_hora")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("integer")
                        .HasColumnName("id_usuario");

                    b.Property<string>("UsuarioNombre")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("usuario_nombre");

                    b.Property<string>("ValoresAnteriores")
                        .HasColumnType("jsonb")
                        .HasColumnName("valores_anteriores");

                    b.Property<string>("ValoresNuevos")
                        .HasColumnType("jsonb")
                        .HasColumnName("valores_nuevos");

                    b.HasKey("IdAuditoria")
                        .HasName("auditoria_pkey");

                    b.ToTable("auditoria", (string)null);
                });

            modelBuilder.Entity("proyecto_venta_stock.Models.CategoriaPermiso", b =>
                {
                    b.Property<int>("IdCategoriaPermiso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_categoria_permiso");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdCategoriaPermiso"));

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("categoria");

                    b.HasKey("IdCategoriaPermiso")
                        .HasName("categoria_permiso_pkey");

                    b.ToTable("categoria_permiso", (string)null);
                });

            modelBuilder.Entity("proyecto_venta_stock.Models.Categorium", b =>
                {
                    b.Property<int>("IdCategoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_categoria");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdCategoria"));

                    b.Property<string>("Categoria")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("categoria");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("descripcion");

                    b.HasKey("IdCategoria")
                        .HasName("categoria_pkey");

                    b.ToTable("categoria", (string)null);
                });

            modelBuilder.Entity("proyecto_venta_stock.Models.Cliente", b =>
                {
                    b.Property<int>("IdCliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_cliente");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdCliente"));

                    b.Property<string>("Apellido")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("apellido");

                    b.Property<string>("Cuit")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("cuit");

                    b.Property<string>("Dni")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("dni");

                    b.Property<DateOnly?>("FechaAlta")
                        .HasColumnType("date")
                        .HasColumnName("fecha_alta");

                    b.Property<DateOnly?>("FechaBaja")
                        .HasColumnType("date")
                        .HasColumnName("fecha_baja");

                    b.Property<string>("Mail")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("mail");

                    b.Property<string>("Nombre")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.Property<string>("RazonSocial")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("razon_social");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("telefono");

                    b.HasKey("IdCliente")
                        .HasName("cliente_pkey");

                    b.ToTable("cliente", (string)null);
                });

            modelBuilder.Entity("proyecto_venta_stock.Models.CodigoBarra", b =>
                {
                    b.Property<int>("IdCodigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_codigo")
                        .HasDefaultValueSql("nextval('codigobarra_id_codigo_seq'::regclass)");

                    b.Property<bool?>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<string>("Codigo")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("codigo");

                    b.Property<int?>("IdProducto")
                        .HasColumnType("integer")
                        .HasColumnName("id_producto");

                    b.Property<bool?>("Prinicial")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("prinicial");

                    b.HasKey("IdCodigo")
                        .HasName("codigobarra_pkey");

                    b.HasIndex("IdProducto");

                    b.HasIndex(new[] { "Codigo" }, "codigobarra_codigo_key")
                        .IsUnique();

                    b.ToTable("codigo_barra", (string)null);
                });

            modelBuilder.Entity("proyecto_venta_stock.Models.Compra", b =>
                {
                    b.Property<int>("IdProducto")
                        .HasColumnType("integer")
                        .HasColumnName("id_producto");

                    b.Property<int>("IdProveedor")
                        .HasColumnType("integer")
                        .HasColumnName("id_proveedor");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date")
                        .HasColumnName("fecha");

                    b.Property<int?>("Cantidad")
                        .HasColumnType("integer")
                        .HasColumnName("cantidad");

                    b.Property<int?>("IdUsuario")
                        .HasColumnType("integer")
                        .HasColumnName("id_usuario");

                    b.Property<decimal?>("PrecioUnitario")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("precio_unitario");

                    b.HasKey("IdProducto", "IdProveedor", "Fecha")
                        .HasName("compra_pkey");

                    b.HasIndex("IdProveedor");

                    b.HasIndex("IdUsuario");

                    b.ToTable("compra", (string)null);
                });

            modelBuilder.Entity("proyecto_venta_stock.Models.CompraProveedor", b =>
                {
                    b.Property<int>("IdCompraProveedor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_compra_proveedor");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdCompraProveedor"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<decimal>("DescuentoTotal")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("descuento_total");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date")
                        .HasColumnName("fecha");

                    b.Property<DateOnly?>("FechaVencimiento")
                        .HasColumnType("date")
                        .HasColumnName("fecha_vencimiento");

                    b.Property<int>("IdProveedor")
                        .HasColumnType("integer")
                        .HasColumnName("id_proveedor");

                    b.Property<int?>("IdUsuario")
                        .HasColumnType("integer")
                        .HasColumnName("id_usuario");

                    b.Property<decimal>("IvaTotal")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("iva_total");

                    b.Property<string>("NumeroComprobante")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("numero_comprobante");

                    b.Property<string>("Observacion")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("observacion");

                    b.Property<decimal>("Subtotal")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("subtotal");

                    b.Property<string>("TipoComprobante")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("tipo_comprobante");

                    b.Property<decimal>("Total")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("total");

                    b.HasKey("IdCompraProveedor")
                        .HasName("compra_proveedor_pkey");

                    b.HasIndex("IdProveedor");

                    b.HasIndex("IdUsuario");

                    b.ToTable("compra_proveedor", (string)null);
                });

            modelBuilder.Entity("proyecto_venta_stock.Models.CompraProveedorDetalle", b =>
                {
                    b.Property<int>("IdCompraProveedorDetalle")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_compra_proveedor_detalle");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdCompraProveedorDetalle"));

                    b.Property<decimal>("Cantidad")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)")
                        .HasColumnName("cantidad");

                    b.Property<decimal>("DescuentoPorcentaje")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("descuento_porcentaje");

                    b.Property<int>("IdCompraProveedor")
                        .HasColumnType("integer")
                        .HasColumnName("id_compra_proveedor");

                    b.Property<int>("IdProducto")
                        .HasColumnType("integer")
                        .HasColumnName("id_producto");

                    b.Property<decimal>("IvaPorcentaje")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("iva_porcentaje");

                    b.Property<decimal>("PrecioUnitario")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("precio_unitario");

                    b.Property<decimal>("Subtotal")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("subtotal");

                    b.Property<decimal>("Total")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("total");

                    b.HasKey("IdCompraProveedorDetalle")
                        .HasName("compra_proveedor_detalle_pkey");

                    b.HasIndex("IdCompraProveedor");

                    b.HasIndex("IdProducto");

                    b.ToTable("compra_proveedor_detalle", (string)null);
                });

            modelBuilder.Entity("proyecto_venta_stock.Models.ConfiguracionCc", b =>
                {
                    b.Property<int>("IdConfig")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_config");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdConfig"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<decimal>("MontoLimite")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("monto_limite");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.HasKey("IdConfig");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("configuracion_cc", null, t =>
                        {
                            t.HasCheckConstraint("CK_configuracion_cc_monto_limite", "monto_limite > 0");
                        });
                });

            modelBuilder.Entity("proyecto_venta_stock.Models.ConfiguracionInteres", b =>
                {
                    b.Property<int>("IdConfig")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_config");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdConfig"));

                    b.Property<int>("DiaVencimiento")
                        .HasColumnType("integer")
                        .HasColumnName("dia_vencimiento");

                    b.Property<bool>("EsActual")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("es_actual");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.Property<decimal>("PorcentajeInteres")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("porcentaje_interes");

                    b.HasKey("IdConfig");

                    b.ToTable("configuracion_interes", (string)null);
                });

            modelBuilder.Entity("proyecto_venta_stock.Models.DetalleVentaPendiente", b =>
                {
                    b.Property<int>("IdDetalle")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_detalle");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdDetalle"));

                    b.Property<decimal>("Cantidad")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)")
                        .HasColumnName("cantidad");

                    b.Property<int>("IdProducto")
                        .HasColumnType("integer")
                        .HasColumnName("id_producto");

                    b.Property<int>("IdVentaPendiente")
                        .HasColumnType("integer")
                        .HasColumnName("id_venta_pendiente");

                    b.Property<decimal>("PrecioVenta")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("precio_venta");

                    b.Property<decimal>("Subtotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("subtotal");

                    b.HasKey("IdDetalle")
                        .HasName("detalle_venta_pendiente_pkey");

                    b.HasIndex("IdProducto");

                    b.HasIndex(new[] { "IdVentaPendiente" }, "idx_detalle_venta_pendiente");

                    b.ToTable("detalle_venta_pendiente", (string)null);
                });

            modelBuilder.Entity("proyecto_venta_stock.Models.DetalleVentum", b =>
                {
                    b.Property<int>("IdVenta")
                        .HasColumnType("integer")
                        .HasColumnName("id_venta");

                    b.Property<int>("IdProducto")
                        .HasColumnType("integer")
                        .HasColumnName("id_producto");

                    b.Property<decimal?>("Cantidad")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)")
                        .HasColumnName("cantidad");

                    b.Property<decimal?>("PrecioVenta")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("precio_venta");

                    b.Property<decimal?>("SubTotal")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("sub_total");

                    b.HasKey("IdVenta", "IdProducto")
                        .HasName("detalleventa_pkey");

                    b.HasIndex("IdProducto");

                    b.ToTable("detalle_venta", (string)null);
                });

            modelBuilder.Entity("proyecto_venta_stock.Models.Estado", b =>
                {
                    b.Property<int>("IdEstado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_estado");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdEstado"));

                    b.Property<string>("Estado1")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("estado");

                    b.HasKey("IdEstado")
                        .HasName("estado_pkey");

                    b.ToTable("estado", (string)null);
                });

            modelBuilder.Entity("proyecto_venta_stock.Models.Ferreteria", b =>
                {
                    b.Property<int>("IdFerreteria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_empresa");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdFerreteria"));

                    b.Property<string>("Cuit")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("cuit");

                    b.Property<string>("Direccion")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("direccion");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("email");

                    b.Property<DateTime>("FechaActualizacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("fecha_actualizacion")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("logo_url");

                    b.Property<string>("Nombre")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nombre");

                    b.Property<string>("Telefono")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("telefono");

                    b.HasKey("IdFerreteria")
                        .HasName("empresa_pkey");

                    b.ToTable("empresa", (string)null);
                });

            modelBuilder.Entity("proyecto_venta_stock.Models.ListaPrecio", b =>
                {
                    b.Property<int>("IdLista")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_lista")
                        .HasDefaultValueSql("nextval('listaprecio_id_lista_seq'::regclass)");

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<DateTime?>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("fecha_creacion")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int?>("IdProveedor")
                        .HasColumnType("integer")
                        .HasColumnName("id_proveedor");

                    b.Property<int?>("IdUsuarioRegistra")
                        .HasColumnType("integer")
                        .HasColumnName("id_usuario_registra");

                    b.Property<string>("Nombre")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("observaciones");

                    b.HasKey("IdLista")
                        .HasName("listaprecio_pkey");

                    b.HasIndex("IdProveedor");

                    b.HasIndex("IdUsuarioRegistra");

                    b.ToTable("lista_precio", (string)null);
                });

            modelBuilder.Entity("proyecto_venta_stock.Models.MedioPago", b =>
                {
                    b.Property<int>("IdMedioPago")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_medio_pago");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdMedioPago"));

                    b.Property<string>("MedioPago1")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("medio_pago");

                    b.HasKey("IdMedioPago")
                        .HasName("medio_pago_pkey");

                    b.ToTable("medio_pago", (string)null);
                });

            modelBuilder.Entity("proyecto_venta_stock.Models.MotivoNotaCredito", b =>
                {
                    b.Property<int>("IdMotivo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_motivo");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdMotivo"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.HasKey("IdMotivo");

                    b.ToTable("motivo_nota_credito", (string)null);
                });

            modelBuilder.Entity("proyecto_venta_stock.Models.MotivoNotaDebito", b =>
                {
                    b.Property<int>("IdMotivo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_motivo");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdMotivo"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("general")
                        .HasColumnName("categoria");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.HasKey("IdMotivo");

                    b.ToTable("motivo_nota_debito", (string)null);
                });

            modelBuilder.Entity("proyecto_venta_stock.Models.MovimientoCc", b =>
                {
                    b.Property<int>("IdMovimiento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_movimiento")
                        .HasDefaultValueSql("nextval('movimientocc_id_movimiento_seq'::regclass)");

                    b.Property<string>("Detalle")
                        .HasColumnType("text")
                        .HasColumnName("detalle");

                    b.Property<bool>("EsAnulado")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("Fecha")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("fecha")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("FechaAutorizacion")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("fecha_autorizacion");

                    b.Property<int?>("IdCliente")
                        .HasColumnType("integer")
                        .HasColumnName("id_cliente");

                    b.Property<int?>("IdEstado")
                        .HasColumnType("integer")
                        .HasColumnName("id_estado");

                    b.Property<int?>("IdMotivoNc")
                        .HasColumnType("integer")
                        .HasColumnName("id_motivo_nc");

                    b.Property<int?>("IdMotivoNd")
                        .HasColumnType("integer")
                        .HasColumnName("id_motivo_nd");

                    b.Property<int?>("IdTipoMovimiento")
                        .HasColumnType("integer")
                        .HasColumnName("id_tipo_movimiento");

                    b.Property<int?>("IdUsuarioAutoriza")
                        .HasColumnType("integer")
                        .HasColumnName("id_usuario_autoriza");

                    b.Property<int?>("IdUsuarioRegistra")
                        .HasColumnType("integer")
                        .HasColumnName("id_usuario_registra");

                    b.Property<int?>("IdVenta")
                        .HasColumnType("integer")
                        .HasColumnName("id_venta");

                    b.Property<decimal?>("Importe")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("importe");

                    b.Property<decimal?>("LimiteCuenta")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("limite_cuenta");

                    b.Property<decimal?>("MontoPagado")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("SaldoActual")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("saldo_actual");

                    b.HasKey("IdMovimiento")
                        .HasName("movimientocc_pkey");

                    b.HasIndex("IdCliente");

                    b.HasIndex("IdEstado");

                    b.HasIndex("IdMotivoNc");

                    b.HasIndex("IdMotivoNd");

                    b.HasIndex("IdTipoMovimiento");

                    b.HasIndex("IdUsuarioAutoriza");

                    b.HasIndex("IdUsuarioRegistra");

                    b.HasIndex("IdVenta");

                    b.ToTable("movimiento_cc", (string)null);
                });

            modelBuilder.Entity("proyecto_venta_stock.Models.MovimientoStock", b =>
                {
                    b.Property<int>("IdMovimientoStock")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_movimiento_stock");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdMovimientoStock"));

                    b.Property<decimal>("Cantidad")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)")
                        .HasColumnName("cantidad");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha");

                    b.Property<int>("IdProducto")
                        .HasColumnType("integer")
                        .HasColumnName("id_producto");

                    b.Property<int>("IdTipoMovimientoStock")
                        .HasColumnType("integer")
                        .HasColumnName("id_tipo_movimiento_stock");

                    b.Property<int?>("IdUsuario")
                        .HasColumnType("integer")
                        .HasColumnName("id_usuario");

                    b.Property<string>("Referencia")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("referencia");

                    b.Property<decimal>("StockResultante")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)")
                        .HasColumnName("stock_resultante");

                    b.HasKey("IdMovimientoStock");

                    b.HasIndex("IdProducto");

                    b.HasIndex("IdTipoMovimientoStock");

                    b.HasIndex("IdUsuario");

                    b.ToTable("movimiento_stock", (string)null);
                });

            modelBuilder.Entity("proyecto_venta_stock.Models.Permiso", b =>
                {
                    b.Property<int>("IdPermiso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_permiso");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdPermiso"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("descripcion");

                    b.Property<int>("IdCategoriaPermiso")
                        .HasColumnType("integer")
                        .HasColumnName("id_categoria_permiso");

                    b.Property<string>("Permiso1")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("permiso");

                    b.HasKey("IdPermiso")
                        .HasName("permiso_pkey");

                    b.HasIndex("IdCategoriaPermiso");

                    b.ToTable("permiso", (string)null);
                });

            modelBuilder.Entity("proyecto_venta_stock.Models.PermisoUsuario", b =>
                {
                    b.Property<int>("IdPermiso")
                        .HasColumnType("integer")
                        .HasColumnName("id_permiso");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("integer")
                        .HasColumnName("id_usuario");

                    b.Property<DateOnly?>("FechaAsignacion")
                        .HasColumnType("date")
                        .HasColumnName("fecha_asignacion");

                    b.HasKey("IdPermiso", "IdUsuario")
                        .HasName("permisousuario_pkey");

                    b.HasIndex("IdUsuario");

                    b.ToTable("permiso_usuario", (string)null);
                });

            modelBuilder.Entity("proyecto_venta_stock.Models.Producto", b =>
                {
                    b.Property<int>("IdProducto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_producto");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdProducto"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("descripcion");

                    b.Property<int?>("IdCategoria")
                        .HasColumnType("integer")
                        .HasColumnName("id_categoria");

                    b.Property<int?>("IdUbicacion")
                        .HasColumnType("integer")
                        .HasColumnName("id_ubicacion");

                    b.Property<int?>("IdUnidadMedida")
                        .HasColumnType("integer")
                        .HasColumnName("id_unidad_medida");

                    b.Property<string>("Marca")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("marca");

                    b.Property<string>("Nombre")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.Property<decimal?>("Precio")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("precio");

                    b.Property<decimal?>("Stock")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)")
                        .HasColumnName("stock");

                    b.Property<decimal?>("StockMinimo")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)")
                        .HasColumnName("stock_minimo");

                    b.Property<bool?>("VentaSinStock")
                        .HasColumnType("boolean")
                        .HasColumnName("venta_sin_stock");

                    b.HasKey("IdProducto")
                        .HasName("producto_pkey");

                    b.HasIndex("IdCategoria");

                    b.HasIndex("IdUbicacion");

                    b.HasIndex("IdUnidadMedida");

                    b.ToTable("producto", (string)null);
                });

            modelBuilder.Entity("proyecto_venta_stock.Models.ProductoListaprecioProveedor", b =>
                {
                    b.Property<int>("IdLista")
                        .HasColumnType("integer")
                        .HasColumnName("id_lista");

                    b.Property<int>("IdProducto")
                        .HasColumnType("integer")
                        .HasColumnName("id_producto");

                    b.Property<decimal?>("Margen")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("margen");

                    b.Property<decimal>("Precio")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("precio");

                    b.HasKey("IdLista", "IdProducto")
                        .HasName("productolistaprecioproveedor_pkey");

                    b.HasIndex("IdProducto");

                    b.ToTable("producto_listaprecio_proveedor", (string)null);
                });

            modelBuilder.Entity("proyecto_venta_stock.Models.Proveedor", b =>
                {
                    b.Property<int>("IdProveedor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_proveedor");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdProveedor"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<string>("Direccion")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("direccion");

                    b.Property<DateTime?>("FechaBaja")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_baja");

                    b.Property<string>("Proveedor1")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("proveedor");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("telefono");

                    b.HasKey("IdProveedor")
                        .HasName("proveedor_pkey");

                    b.ToTable("proveedor", (string)null);
                });

            modelBuilder.Entity("proyecto_venta_stock.Models.TipoMovimiento", b =>
                {
                    b.Property<int>("IdMovimiento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_movimiento")
                        .HasDefaultValueSql("nextval('tipomovimiento_id_movimiento_seq'::regclass)");

                    b.Property<string>("Accion")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("accion");

                    b.Property<string>("Nombre")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nombre");

                    b.HasKey("IdMovimiento")
                        .HasName("tipomovimiento_pkey");

                    b.ToTable("tipo_movimiento", (string)null);
                });

            modelBuilder.Entity("proyecto_venta_stock.Models.TipoMovimientoStock", b =>
                {
                    b.Property<int>("IdTipoMovimientoStock")
                        .HasColumnType("integer")
                        .HasColumnName("id_tipo_movimiento_stock");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("descripcion");

                    b.Property<string>("Nombre")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nombre");

                    b.HasKey("IdTipoMovimientoStock");

                    b.ToTable("tipo_movimiento_stock", (string)null);

                    b.HasData(
                        new
                        {
                            IdTipoMovimientoStock = 1,
                            Descripcion = "Incremento de stock por recepción de mercadería de proveedor.",
                            Nombre = "Ingreso por Compra"
                        },
                        new
                        {
                            IdTipoMovimientoStock = 2,
                            Descripcion = "Reducción de stock por venta a cliente.",
                            Nombre = "Egreso por Venta"
                        },
                        new
                        {
                            IdTipoMovimientoStock = 3,
                            Descripcion = "Restitución de stock al anular una venta.",
                            Nombre = "Reingreso por Anulación de Venta"
                        },
                        new
                        {
                            IdTipoMovimientoStock = 4,
                            Descripcion = "Reducción de stock al anular o revertir una compra a proveedor.",
                            Nombre = "Egreso por Anulación de Compra"
                        },
                        new
                        {
                            IdTipoMovimientoStock = 5,
                            Descripcion = "Incremento manual de stock (ej: sobrante en inventario físico).",
                            Nombre = "Ajuste Positivo Manual"
                        },
                        new
                        {
                            IdTipoMovimientoStock = 6,
                            Descripcion = "Reducción manual de stock (ej: faltante en inventario físico).",
                            Nombre = "Ajuste Negativo Manual"
                        },
                        new
                        {
                            IdTipoMovimientoStock = 7,
                            Descripcion = "Retiro de mercadería para uso interno o personal del dueño.",
                            Nombre = "Consumo Interno Dueño"
                        });
                });

            modelBuilder.Entity("proyecto_venta_stock.Models.Ubicacion", b =>
                {
                    b.Property<int>("IdUbicacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_ubicacion");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdUbicacion"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<int?>("Fila")
                        .HasColumnType("integer")
                        .HasColumnName("fila");

                    b.Property<int?>("Nivel")
                        .HasColumnType("integer")
                        .HasColumnName("nivel");

                    b.Property<string>("Seccion")
                        .HasColumnType("text")
                        .HasColumnName("seccion");

                    b.HasKey("IdUbicacion")
                        .HasName("ubicacion_pkey");

                    b.ToTable("ubicacion", (string)null);
                });

            modelBuilder.Entity("proyecto_venta_stock.Models.UnidadMedida", b =>
                {
                    b.Property<int>("IdUnidadMedida")
                        .HasColumnType("integer")
                        .HasColumnName("id_unidad_medida");

                    b.Property<string>("Abreviatura")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("abreviatura");

                    b.Property<string>("Nombre")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nombre");

                    b.HasKey("IdUnidadMedida");

                    b.ToTable("unidad_medida", (string)null);

                    b.HasData(
                        new
                        {
                            IdUnidadMedida = 1,
                            Abreviatura = "u",
                            Nombre = "Unidad"
                        },
                        new
                        {
                            IdUnidadMedida = 2,
                            Abreviatura = "kg",
                            Nombre = "Kilogramo"
                        },
                        new
                        {
                            IdUnidadMedida = 3,
                            Abreviatura = "m",
                            Nombre = "Metro"
                        },
                        new
                        {
                            IdUnidadMedida = 4,
                            Abreviatura = "l",
                            Nombre = "Litro"
                        });
                });

            modelBuilder.Entity("proyecto_venta_stock.Models.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_usuario");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdUsuario"));

                    b.Property<string>("Apellido")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("apellido");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("email");

                    b.Property<DateOnly?>("FechaAlta")
                        .HasColumnType("date")
                        .HasColumnName("fecha_alta");

                    b.Property<DateOnly?>("FechaBaja")
                        .HasColumnType("date")
                        .HasColumnName("fecha_baja");

                    b.Property<string>("Nombre")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.Property<string>("Password")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("password");

                    b.Property<string>("Rol")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("rol");

                    b.Property<bool>("Root")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("root");

                    b.Property<string>("Usuario1")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("usuario");

                    b.HasKey("IdUsuario")
                        .HasName("usuario_pkey");

                    b.HasIndex(new[] { "Usuario1" }, "usuario_usuario_key")
                        .IsUnique();

                    b.ToTable("usuario", (string)null);
                });

            modelBuilder.Entity("proyecto_venta_stock.Models.VentaPendiente", b =>
                {
                    b.Property<int>("IdVentaPendiente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_venta_pendiente");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdVentaPendiente"));

                    b.Property<string>("CodigoVenta")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("codigo_venta");

                    b.Property<decimal?>("Excedente")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("excedente")
                        .HasComment("Monto que excede el límite de crédito");

                    b.Property<DateTime?>("FechaAutorizacion")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("fecha_autorizacion");

                    b.Property<DateTime>("FechaRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("fecha_registro")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("IdCliente")
                        .HasColumnType("integer")
                        .HasColumnName("id_cliente");

                    b.Property<int>("IdEstado")
                        .HasColumnType("integer")
                        .HasColumnName("id_estado");

                    b.Property<int>("IdMedioPago")
                        .HasColumnType("integer")
                        .HasColumnName("id_medio_pago");

                    b.Property<int?>("IdUsuarioAutoriza")
                        .HasColumnType("integer")
                        .HasColumnName("id_usuario_autoriza");

                    b.Property<int>("IdUsuarioVendedor")
                        .HasColumnType("integer")
                        .HasColumnName("id_usuario_vendedor");

                    b.Property<int?>("IdVentaGenerada")
                        .HasColumnType("integer")
                        .HasColumnName("id_venta_generada")
                        .HasComment("Referencia a la venta definitiva si fue aprobada");

                    b.Property<decimal?>("LimiteCuenta")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("limite_cuenta");

                    b.Property<string>("ObservacionesAutorizacion")
                        .HasColumnType("text")
                        .HasColumnName("observaciones_autorizacion");

                    b.Property<decimal?>("SaldoActual")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("saldo_actual");

                    b.Property<decimal?>("SaldoDespuesVenta")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("saldo_despues_venta");

                    b.Property<decimal>("Total")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("total");

                    b.HasKey("IdVentaPendiente")
                        .HasName("venta_pendiente_pkey");

                    b.HasIndex("IdMedioPago");

                    b.HasIndex("IdUsuarioAutoriza");

                    b.HasIndex("IdVentaGenerada");

                    b.HasIndex(new[] { "IdCliente" }, "idx_venta_pendiente_cliente");

                    b.HasIndex(new[] { "IdEstado" }, "idx_venta_pendiente_estado");

                    b.HasIndex(new[] { "FechaRegistro" }, "idx_venta_pendiente_fecha")
                        .IsDescending();

                    b.HasIndex(new[] { "IdUsuarioVendedor" }, "idx_venta_pendiente_vendedor");

                    b.HasIndex(new[] { "CodigoVenta" }, "venta_pendiente_codigo_venta_key")
                        .IsUnique();

                    b.ToTable("venta_pendiente", null, t =>
                        {
                            t.HasComment("Ventas que exceden el límite de crédito y requieren autorización");
                        });
                });

            modelBuilder.Entity("proyecto_venta_stock.Models.Ventum", b =>
                {
                    b.Property<int>("IdVenta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_venta");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdVenta"));

                    b.Property<string>("CodigoVenta")
                        .HasColumnType("text")
                        .HasColumnName("codigo_venta");

                    b.Property<string>("DetalleNc")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("detalle_nc");

                    b.Property<DateTime?>("Fecha")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("fecha")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int?>("IdCliente")
                        .HasColumnType("integer")
                        .HasColumnName("id_cliente");

                    b.Property<int?>("IdEstado")
                        .HasColumnType("integer")
                        .HasColumnName("id_estado");

                    b.Property<int?>("IdMedioPago")
                        .HasColumnType("integer")
                        .HasColumnName("id_medio_pago");

                    b.Property<int?>("IdMotivoNc")
                        .HasColumnType("integer")
                        .HasColumnName("id_motivo_nc");

                    b.Property<int?>("IdUsuario")
                        .HasColumnType("integer")
                        .HasColumnName("id_usuario");

                    b.Property<decimal?>("Total")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("total");

                    b.HasKey("IdVenta")
                        .HasName("venta_pkey");

                    b.HasIndex("IdCliente");

                    b.HasIndex("IdEstado");

                    b.HasIndex("IdMedioPago");

                    b.HasIndex("IdMotivoNc");

                    b.HasIndex("IdUsuario");

                    b.ToTable("venta", (string)null);
                });

            modelBuilder.Entity("proyecto_venta_stock.Models.CodigoBarra", b =>
                {
                    b.HasOne("proyecto_venta_stock.Models.Producto", "IdProductoNavigation")
                        .WithMany("CodigoBarras")
                        .HasForeignKey("IdProducto")
                        .HasConstraintName("codigobarra_id_producto_fkey");

                    b.Navigation("IdProductoNavigation");
                });

            modelBuilder.Entity("proyecto_venta_stock.Models.Compra", b =>
                {
                    b.HasOne("proyecto_venta_stock.Models.Producto", "IdProductoNavigation")
                        .WithMany("Compras")
                        .HasForeignKey("IdProducto")
                        .IsRequired()
                        .HasConstraintName("compra_id_producto_fkey");

                    b.HasOne("proyecto_venta_stock.Models.Proveedor", "IdProveedorNavigation")
                        .WithMany("Compras")
                        .HasForeignKey("IdProveedor")
                        .IsRequired()
                        .HasConstraintName("compra_id_proveedor_fkey");

                    b.HasOne("proyecto_venta_stock.Models.Usuario", "IdUsuarioNavigation")
                        .WithMany("Compras")
                        .HasForeignKey("IdUsuario")
                        .HasConstraintName("compra_id_usuario_fkey");

                    b.Navigation("IdProductoNavigation");

                    b.Navigation("IdProveedorNavigation");

                    b.Navigation("IdUsuarioNavigation");
                });

            modelBuilder.Entity("proyecto_venta_stock.Models.CompraProveedor", b =>
                {
                    b.HasOne("proyecto_venta_stock.Models.Proveedor", "IdProveedorNavigation")
                        .WithMany()
                        .HasForeignKey("IdProveedor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("compra_proveedor_id_proveedor_fkey");

                    b.HasOne("proyecto_venta_stock.Models.Usuario", "IdUsuarioNavigation")
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .HasConstraintName("compra_proveedor_id_usuario_fkey");

                    b.Navigation("IdProveedorNavigation");

                    b.Navigation("IdUsuarioNavigation");
                });

            modelBuilder.Entity("proyecto_venta_stock.Models.CompraProveedorDetalle", b =>
                {
                    b.HasOne("proyecto_venta_stock.Models.CompraProveedor", "IdCompraProveedorNavigation")
                        .WithMany("CompraProveedorDetalles")
                        .HasForeignKey("IdCompraProveedor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("compra_proveedor_detalle_id_compra_proveedor_fkey");

                    b.HasOne("proyecto_venta_stock.Models.Producto", "IdProductoNavigation")
                        .WithMany()
                        .HasForeignKey("IdProducto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("compra_proveedor_detalle_id_producto_fkey");

                    b.Navigation("IdCompraProveedorNavigation");

                    b.Navigation("IdProductoNavigation");
                });

            modelBuilder.Entity("proyecto_venta_stock.Models.DetalleVentaPendiente", b =>
                {
                    b.HasOne("proyecto_venta_stock.Models.Producto", "IdProductoNavigation")
                        .WithMany()
                        .HasForeignKey("IdProducto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("detalle_venta_pendiente_id_producto_fkey");

                    b.HasOne("proyecto_venta_stock.Models.VentaPendiente", "IdVentaPendienteNavigation")
                        .WithMany("DetalleVentaPendientes")
                        .HasForeignKey("IdVentaPendiente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("detalle_venta_pendiente_id_venta_pendiente_fkey");

                    b.Navigation("IdProductoNavigation");

                    b.Navigation("IdVentaPendienteNavigation");
                });

            modelBuilder.Entity("proyecto_venta_stock.Models.DetalleVentum", b =>
                {
                    b.HasOne("proyecto_venta_stock.Models.Producto", "IdProductoNavigation")
                        .WithMany("DetalleVenta")
                        .HasForeignKey("IdProducto")
                        .IsRequired()
                        .HasConstraintName("detalleventa_id_producto_fkey");

                    b.HasOne("proyecto_venta_stock.Models.Ventum", "IdVentaNavigation")
                        .WithMany("DetalleVenta")
                        .HasForeignKey("IdVenta")
                        .IsRequired()
                        .HasConstraintName("detalleventa_id_venta_fkey");

                    b.Navigation("IdProductoNavigation");

                    b.Navigation("IdVentaNavigation");
                });

            modelBuilder.Entity("proyecto_venta_stock.Models.ListaPrecio", b =>
                {
                    b.HasOne("proyecto_venta_stock.Models.Proveedor", "IdProveedorNavigation")
                        .WithMany("ListaPrecios")
                        .HasForeignKey("IdProveedor")
                        .HasConstraintName("listaprecio_id_proveedor_fkey");

                    b.HasOne("proyecto_venta_stock.Models.Usuario", "IdUsuarioRegistraNavigation")
                        .WithMany("ListaPrecios")
                        .HasForeignKey("IdUsuarioRegistra")
                        .HasConstraintName("listaprecio_id_usuario_registra_fkey");

                    b.Navigation("IdProveedorNavigation");

                    b.Navigation("IdUsuarioRegistraNavigation");
                });

            modelBuilder.Entity("proyecto_venta_stock.Models.MovimientoCc", b =>
                {
                    b.HasOne("proyecto_venta_stock.Models.Cliente", "IdClienteNavigation")
                        .WithMany("MovimientoCcs")
                        .HasForeignKey("IdCliente")
                        .HasConstraintName("movimientocc_id_cliente_fkey");

                    b.HasOne("proyecto_venta_stock.Models.Estado", "IdEstadoNavigation")
                        .WithMany("MovimientoCcs")
                        .HasForeignKey("IdEstado")
                        .HasConstraintName("movimientocc_id_estado_fkey");

                    b.HasOne("proyecto_venta_stock.Models.MotivoNotaCredito", "IdMotivoNcNavigation")
                        .WithMany()
                        .HasForeignKey("IdMotivoNc")
                        .HasConstraintName("fk_movimiento_cc_motivo_nc");

                    b.HasOne("proyecto_venta_stock.Models.MotivoNotaDebito", "IdMotivoNdNavigation")
                        .WithMany()
                        .HasForeignKey("IdMotivoNd")
                        .HasConstraintName("fk_movimiento_cc_motivo_nd");

                    b.HasOne("proyecto_venta_stock.Models.TipoMovimiento", "IdTipoMovimientoNavigation")
                        .WithMany("MovimientoCcs")
                        .HasForeignKey("IdTipoMovimiento")
                        .HasConstraintName("movimientocc_id_tipo_movimiento_fkey");

                    b.HasOne("proyecto_venta_stock.Models.Usuario", "IdUsuarioAutorizaNavigation")
                        .WithMany("MovimientoCcIdUsuarioAutorizaNavigations")
                        .HasForeignKey("IdUsuarioAutoriza")
                        .HasConstraintName("movimientocc_id_usuario_autoriza_fkey");

                    b.HasOne("proyecto_venta_stock.Models.Usuario", "IdUsuarioRegistraNavigation")
                        .WithMany("MovimientoCcIdUsuarioRegistraNavigations")
                        .HasForeignKey("IdUsuarioRegistra")
                        .HasConstraintName("movimientocc_id_usuario_registra_fkey");

                    b.HasOne("proyecto_venta_stock.Models.Ventum", "IdVentaNavigation")
                        .WithMany("MovimientoCcs")
                        .HasForeignKey("IdVenta")
                        .HasConstraintName("movimientocc_id_venta_fkey");

                    b.Navigation("IdClienteNavigation");

                    b.Navigation("IdEstadoNavigation");

                    b.Navigation("IdMotivoNcNavigation");

                    b.Navigation("IdMotivoNdNavigation");

                    b.Navigation("IdTipoMovimientoNavigation");

                    b.Navigation("IdUsuarioAutorizaNavigation");

                    b.Navigation("IdUsuarioRegistraNavigation");

                    b.Navigation("IdVentaNavigation");
                });

            modelBuilder.Entity("proyecto_venta_stock.Models.MovimientoStock", b =>
                {
                    b.HasOne("proyecto_venta_stock.Models.Producto", "IdProductoNavigation")
                        .WithMany()
                        .HasForeignKey("IdProducto")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_movimientostock_producto");

                    b.HasOne("proyecto_venta_stock.Models.TipoMovimientoStock", "IdTipoMovimientoStockNavigation")
                        .WithMany("MovimientosStock")
                        .HasForeignKey("IdTipoMovimientoStock")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_movimientostock_tipo");

                    b.HasOne("proyecto_venta_stock.Models.Usuario", "IdUsuarioNavigation")
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_movimientostock_usuario");

                    b.Navigation("IdProductoNavigation");

                    b.Navigation("IdTipoMovimientoStockNavigation");

                    b.Navigation("IdUsuarioNavigation");
                });

            modelBuilder.Entity("proyecto_venta_stock.Models.Permiso", b =>
                {
                    b.HasOne("proyecto_venta_stock.Models.CategoriaPermiso", "CategoriaPermiso")
                        .WithMany("Permisos")
                        .HasForeignKey("IdCategoriaPermiso")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("permiso_id_categoria_permiso_fkey");

                    b.Navigation("CategoriaPermiso");
                });

            modelBuilder.Entity("proyecto_venta_stock.Models.PermisoUsuario", b =>
                {
                    b.HasOne("proyecto_venta_stock.Models.Permiso", "IdPermisoNavigation")
                        .WithMany("PermisoUsuarios")
                        .HasForeignKey("IdPermiso")
                        .IsRequired()
                        .HasConstraintName("permisousuario_id_permiso_fkey");

                    b.HasOne("proyecto_venta_stock.Models.Usuario", "IdUsuarioNavigation")
                        .WithMany("PermisoUsuarios")
                        .HasForeignKey("IdUsuario")
                        .IsRequired()
                        .HasConstraintName("permisousuario_id_usuario_fkey");

                    b.Navigation("IdPermisoNavigation");

                    b.Navigation("IdUsuarioNavigation");
                });

            modelBuilder.Entity("proyecto_venta_stock.Models.Producto", b =>
                {
                    b.HasOne("proyecto_venta_stock.Models.Categorium", "IdCategoriaNavigation")
                        .WithMany("Productos")
                        .HasForeignKey("IdCategoria")
                        .HasConstraintName("producto_id_categoria_fkey");

                    b.HasOne("proyecto_venta_stock.Models.Ubicacion", "IdUbicacionNavigation")
                        .WithMany("Productos")
                        .HasForeignKey("IdUbicacion")
                        .HasConstraintName("producto_id_ubicacion_fkey");

                    b.HasOne("proyecto_venta_stock.Models.UnidadMedida", "IdUnidadMedidaNavigation")
                        .WithMany("Productos")
                        .HasForeignKey("IdUnidadMedida")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("producto_id_unidad_medida_fkey");

                    b.Navigation("IdCategoriaNavigation");

                    b.Navigation("IdUbicacionNavigation");

                    b.Navigation("IdUnidadMedidaNavigation");
                });

            modelBuilder.Entity("proyecto_venta_stock.Models.ProductoListaprecioProveedor", b =>
                {
                    b.HasOne("proyecto_venta_stock.Models.ListaPrecio", "IdListaNavigation")
                        .WithMany("ProductoListaprecioProveedors")
                        .HasForeignKey("IdLista")
                        .IsRequired()
                        .HasConstraintName("productolistaprecioproveedor_id_lista_fkey");

                    b.HasOne("proyecto_venta_stock.Models.Producto", "IdProductoNavigation")
                        .WithMany("ProductoListaprecioProveedors")
                        .HasForeignKey("IdProducto")
                        .IsRequired()
                        .HasConstraintName("productolistaprecioproveedor_id_producto_fkey");

                    b.Navigation("IdListaNavigation");

                    b.Navigation("IdProductoNavigation");
                });

            modelBuilder.Entity("proyecto_venta_stock.Models.VentaPendiente", b =>
                {
                    b.HasOne("proyecto_venta_stock.Models.Cliente", "IdClienteNavigation")
                        .WithMany()
                        .HasForeignKey("IdCliente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("venta_pendiente_id_cliente_fkey");

                    b.HasOne("proyecto_venta_stock.Models.Estado", "IdEstadoNavigation")
                        .WithMany()
                        .HasForeignKey("IdEstado")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("venta_pendiente_id_estado_fkey");

                    b.HasOne("proyecto_venta_stock.Models.MedioPago", "IdMedioPagoNavigation")
                        .WithMany()
                        .HasForeignKey("IdMedioPago")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("venta_pendiente_id_medio_pago_fkey");

                    b.HasOne("proyecto_venta_stock.Models.Usuario", "IdUsuarioAutorizaNavigation")
                        .WithMany()
                        .HasForeignKey("IdUsuarioAutoriza")
                        .HasConstraintName("venta_pendiente_id_usuario_autoriza_fkey");

                    b.HasOne("proyecto_venta_stock.Models.Usuario", "IdUsuarioVendedorNavigation")
                        .WithMany()
                        .HasForeignKey("IdUsuarioVendedor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("venta_pendiente_id_usuario_vendedor_fkey");

                    b.HasOne("proyecto_venta_stock.Models.Ventum", "IdVentaGeneradaNavigation")
                        .WithMany()
                        .HasForeignKey("IdVentaGenerada")
                        .HasConstraintName("venta_pendiente_id_venta_generada_fkey");

                    b.Navigation("IdClienteNavigation");

                    b.Navigation("IdEstadoNavigation");

                    b.Navigation("IdMedioPagoNavigation");

                    b.Navigation("IdUsuarioAutorizaNavigation");

                    b.Navigation("IdUsuarioVendedorNavigation");

                    b.Navigation("IdVentaGeneradaNavigation");
                });

            modelBuilder.Entity("proyecto_venta_stock.Models.Ventum", b =>
                {
                    b.HasOne("proyecto_venta_stock.Models.Cliente", "IdClienteNavigation")
                        .WithMany("Venta")
                        .HasForeignKey("IdCliente")
                        .HasConstraintName("venta_id_cliente_fkey");

                    b.HasOne("proyecto_venta_stock.Models.Estado", "IdEstadoNavigation")
                        .WithMany("Venta")
                        .HasForeignKey("IdEstado")
                        .HasConstraintName("venta_id_estado_fkey");

                    b.HasOne("proyecto_venta_stock.Models.MedioPago", "IdMedioPagoNavigation")
                        .WithMany("Venta")
                        .HasForeignKey("IdMedioPago")
                        .HasConstraintName("venta_id_medio_pago_fkey");

                    b.HasOne("proyecto_venta_stock.Models.MotivoNotaCredito", "IdMotivoNcNavigation")
                        .WithMany()
                        .HasForeignKey("IdMotivoNc")
                        .HasConstraintName("fk_venta_motivo_nc");

                    b.HasOne("proyecto_venta_stock.Models.Usuario", "IdUsuarioNavigation")
                        .WithMany("Venta")
                        .HasForeignKey("IdUsuario")
                        .HasConstraintName("venta_id_usuario_fkey");

                    b.Navigation("IdClienteNavigation");

                    b.Navigation("IdEstadoNavigation");

                    b.Navigation("IdMedioPagoNavigation");

                    b.Navigation("IdMotivoNcNavigation");

                    b.Navigation("IdUsuarioNavigation");
                });

            modelBuilder.Entity("proyecto_venta_stock.Models.CategoriaPermiso", b =>
                {
                    b.Navigation("Permisos");
                });

            modelBuilder.Entity("proyecto_venta_stock.Models.Categorium", b =>
                {
                    b.Navigation("Productos");
                });

            modelBuilder.Entity("proyecto_venta_stock.Models.Cliente", b =>
                {
                    b.Navigation("MovimientoCcs");

                    b.Navigation("Venta");
                });

            modelBuilder.Entity("proyecto_venta_stock.Models.CompraProveedor", b =>
                {
                    b.Navigation("CompraProveedorDetalles");
                });

            modelBuilder.Entity("proyecto_venta_stock.Models.Estado", b =>
                {
                    b.Navigation("MovimientoCcs");

                    b.Navigation("Venta");
                });

            modelBuilder.Entity("proyecto_venta_stock.Models.ListaPrecio", b =>
                {
                    b.Navigation("ProductoListaprecioProveedors");
                });

            modelBuilder.Entity("proyecto_venta_stock.Models.MedioPago", b =>
                {
                    b.Navigation("Venta");
                });

            modelBuilder.Entity("proyecto_venta_stock.Models.Permiso", b =>
                {
                    b.Navigation("PermisoUsuarios");
                });

            modelBuilder.Entity("proyecto_venta_stock.Models.Producto", b =>
                {
                    b.Navigation("CodigoBarras");

                    b.Navigation("Compras");

                    b.Navigation("DetalleVenta");

                    b.Navigation("ProductoListaprecioProveedors");
                });

            modelBuilder.Entity("proyecto_venta_stock.Models.Proveedor", b =>
                {
                    b.Navigation("Compras");

                    b.Navigation("ListaPrecios");
                });

            modelBuilder.Entity("proyecto_venta_stock.Models.TipoMovimiento", b =>
                {
                    b.Navigation("MovimientoCcs");
                });

            modelBuilder.Entity("proyecto_venta_stock.Models.TipoMovimientoStock", b =>
                {
                    b.Navigation("MovimientosStock");
                });

            modelBuilder.Entity("proyecto_venta_stock.Models.Ubicacion", b =>
                {
                    b.Navigation("Productos");
                });

            modelBuilder.Entity("proyecto_venta_stock.Models.UnidadMedida", b =>
                {
                    b.Navigation("Productos");
                });

            modelBuilder.Entity("proyecto_venta_stock.Models.Usuario", b =>
                {
                    b.Navigation("Compras");

                    b.Navigation("ListaPrecios");

                    b.Navigation("MovimientoCcIdUsuarioAutorizaNavigations");

                    b.Navigation("MovimientoCcIdUsuarioRegistraNavigations");

                    b.Navigation("PermisoUsuarios");

                    b.Navigation("Venta");
                });

            modelBuilder.Entity("proyecto_venta_stock.Models.VentaPendiente", b =>
                {
                    b.Navigation("DetalleVentaPendientes");
                });

            modelBuilder.Entity("proyecto_venta_stock.Models.Ventum", b =>
                {
                    b.Navigation("DetalleVenta");

                    b.Navigation("MovimientoCcs");
                });
#pragma warning restore 612, 618
        }
    }
}
